### ISSUE TITLE
Why does eth_signTypedData_v4 return such a long signature?

### ISSUE THREAD

**Issue by web-crab** [immutable/ts-immutable-sdk#1765]
```ts
const sign = async (provider: Provider) => {
  const [address] = await provider.request({ method: 'eth_requestAccounts' })
  const domain = {
    name: window.location.hostname,
    chainId: '13473',
  }
  const types = {
    EIP712Domain: [
      { name: 'name', type: 'string' },
      { name: 'chainId', type: 'uint256' },
    ],
    Test: [{ name: 'value', type: 'string' }],
  }
  const message = { value: 'Test' }
  const typedData = { domain, types, message, primaryType: 'Test' }
  
  return provider.request({
    method: 'eth_signTypedData_v4',
    params: [address, typedData],
  })
}
```

**MetaMask**:
`"0x7e841588b057552389a47f8f7644dda85ba9b6c4c8345e7554ce3888af4c95ab1e4b8dc56739026b98fd79f3ec1584484e60f4acdcc2d7f9ea93d501e1c5aa8c1c"` (132 chars)

**Coinbase Wallet**:
`"0xd97a2ae069b61e3aa74ecff50611e71f5fff7f94e2d8c2fdf3a972fcae90a96100788fb9b7a056554f5ba88437e606aacde1d080bcd9382235be210aab9648871c"` (132 chars)

**Immutable Passport**:
`"0x000200017610557ab9da6383edf2646ac09dd3ce84b9e943481825b5baea7447ee0d27a332c08ec4acccdfb8d59bd3f8fd216c32d1ba9af33a722de2bda09a82f816d3891b020201cff469e561d9dce5b1185cd2ac1fa961f8fbde61004391e05988f0496e8980efa1c08b586a61d05c0f4c33f10bb87bbb580d1dbd689447839d28c80a5f70e8e788ca71618aeb49196aad975d05b200d731373522d4961c0103"` (324 chars)

**Comment by wdinau** [comment]
Hi @web-crab 
Could you help us understand the actual problem or error you have experienced?
How is the Passport signature blocking you in development of passport integration?

If you [verify the signature](https://docs.immutable.com/docs/zkevm/products/passport/wallet/rpc-methods/eth_signtypeddata/), is it not a valid Hex value?

**Comment by wdinau** [comment]
EOAs use EC to generate signatures and they’re typically 65 bytes. Passport in zkEVM is technically a smart contract wallet and uses a different scheme (combines Magic EOA signature + an Immutable signature).

In order to validate that signature you’ll have to use: https://eips.ethereum.org/EIPS/eip-1271
Verification code is in the link I attached above. Also viewable at [here](https://github.com/immutable/ts-immutable-sdk/blob/main/packages/passport/sdk-sample-app/src/components/zkevm/EthSignTypedDataV4Examples/isSignatureValid.ts)

The signature verification of a smart contract wallet is to be delegated to a smart contract as their signing implementation may change. I.e. there are two paths to verify signatures:
* EOA: traditional EC signature verification,
* Smart Contract wallet (in this case Passport) -> EIP-1271.

This is applicable to all other systems Immutable is building in zkEVM, such as the orderbook.

*** notes: Order Book validates 3 types of signatures, all done on-chain:
* Standard 65 byte
* Compact 64 byte - https://eips.ethereum.org/EIPS/eip-2098
* EIP-1271
